"""initial cloud schema

Revision ID: 0fa3d71696f3
Revises: 
Create Date: 2026-07-24 00:19:59.789644
"""
from alembic import op
import sqlalchemy as sa


revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_subject', ['subject_type', 'subject_id'], unique=False)
        batch_op.create_index('ix_audit_ts', ['ts'], unique=False)

    op.create_table('auth_throttle',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('identifier', sa.String(length=320), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'identifier', name='uq_throttle_scope_identifier')
    )
    op.create_table('plans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('max_devices', sa.Integer(), nullable=False),
    sa.Column('max_profiles', sa.Integer(), nullable=False),
    sa.Column('max_sessions', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('update_releases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('min_supported_version', sa.String(length=32), nullable=False),
    sa.Column('artifact_url', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("channel in ('stable','beta')", name='ck_release_channel'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'version', name='uq_release_channel_version')
    )
    with op.batch_alter_table('update_releases', schema=None) as batch_op:
        batch_op.create_index('ix_releases_channel_published', ['channel', 'published_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role in ('user','admin')", name='ck_users_role'),
    sa.CheckConstraint("status in ('unverified','active','suspended')", name='ck_users_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('activation_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('verifier', sa.String(length=64), nullable=False),
    sa.Column('lookup_prefix', sa.String(length=24), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses_remaining', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('active','suspended','revoked')", name='ck_activation_status'),
    sa.CheckConstraint('uses_remaining >= 0', name='ck_activation_uses_nonneg'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verifier', name='uq_activation_verifier')
    )
    with op.batch_alter_table('activation_keys', schema=None) as batch_op:
        batch_op.create_index('ix_activation_lookup_prefix', ['lookup_prefix'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('public_key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'public_key', name='uq_device_user_key')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index('ix_devices_user_active', ['user_id', 'revoked_at'], unique=False)

    op.create_table('email_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_email_verif_token')
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.create_index('ix_email_verif_user', ['user_id'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index('ix_idempotency_expires', ['expires_at'], unique=False)

    op.create_table('oauth_authorization_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('code_challenge', sa.String(length=128), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=8), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("code_challenge_method in ('S256')", name='ck_oauth_pkce_method'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash', name='uq_oauth_code_hash')
    )
    with op.batch_alter_table('oauth_authorization_codes', schema=None) as batch_op:
        batch_op.create_index('ix_oauth_code_user', ['user_id'], unique=False)

    op.create_table('password_resets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_password_reset_token')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index('ix_password_reset_user', ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_ref', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('active','past_due','canceled','incomplete')", name='ck_subscriptions_status'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('ix_subscriptions_plan', ['plan_id'], unique=False)
        batch_op.create_index('ix_subscriptions_user', ['user_id'], unique=False)

    op.create_table('entitlements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('key_id', sa.String(length=36), nullable=True),
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('offline_grace_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['key_id'], ['activation_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entitlements', schema=None) as batch_op:
        batch_op.create_index('ix_entitlements_user_device', ['user_id', 'device_id'], unique=False)

    op.create_table('redemptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['key_id'], ['activation_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_id', 'device_id', name='uq_redemption_key_device')
    )
    with op.batch_alter_table('redemptions', schema=None) as batch_op:
        batch_op.create_index('ix_redemptions_user', ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reuse_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash', name='uq_session_refresh_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_device', ['device_id'], unique=False)
        batch_op.create_index('ix_sessions_family', ['family_id'], unique=False)
        batch_op.create_index('ix_sessions_user_active', ['user_id', 'revoked_at'], unique=False)

    # ### end Alembic commands ###

    # DB-review S4: DB-level defense-in-depth for case-insensitive email uniqueness.
    # Postgres only (a functional index); SQLite tests rely on the app's NFC+casefold
    # normalization + the plain UNIQUE(email).
    if op.get_bind().dialect.name == "postgresql":
        op.create_index(
            "uq_users_email_lower", "users", [sa.text("lower(email)")], unique=True
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.drop_index("uq_users_email_lower", table_name="users")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_active')
        batch_op.drop_index('ix_sessions_family')
        batch_op.drop_index('ix_sessions_device')

    op.drop_table('sessions')
    with op.batch_alter_table('redemptions', schema=None) as batch_op:
        batch_op.drop_index('ix_redemptions_user')

    op.drop_table('redemptions')
    with op.batch_alter_table('entitlements', schema=None) as batch_op:
        batch_op.drop_index('ix_entitlements_user_device')

    op.drop_table('entitlements')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_subscriptions_user')
        batch_op.drop_index('ix_subscriptions_plan')

    op.drop_table('subscriptions')
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index('ix_password_reset_user')

    op.drop_table('password_resets')
    with op.batch_alter_table('oauth_authorization_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_oauth_code_user')

    op.drop_table('oauth_authorization_codes')
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_idempotency_expires')

    op.drop_table('idempotency_keys')
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_index('ix_email_verif_user')

    op.drop_table('email_verifications')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index('ix_devices_user_active')

    op.drop_table('devices')
    with op.batch_alter_table('activation_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_activation_lookup_prefix')

    op.drop_table('activation_keys')
    op.drop_table('users')
    with op.batch_alter_table('update_releases', schema=None) as batch_op:
        batch_op.drop_index('ix_releases_channel_published')

    op.drop_table('update_releases')
    op.drop_table('plans')
    op.drop_table('auth_throttle')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_ts')
        batch_op.drop_index('ix_audit_subject')

    op.drop_table('audit_events')
    # ### end Alembic commands ###
